config/routes.rb
Rails.application.routes.draw do

  root "categories#index"

  post "/archive_user", to: "users#archive_user"


  resources :categories, except: [:edit] do
    resources :memes, except: [:edit, :index]
  end

  resources :memes, only: [:show] do
    resource :reviews, except: [:edit, :show, :index]
  end


  namespace :api do
    namespace :v1 do
      resources :categories, only: [:index, :show, :create] do
        resources :memes, only: [:show, :create]
      end
      resources :memes, only: [:show, :create] do
        resources :reviews, only: [:index, :show, :create] do
          resources :upvotes, only: [:index, :create, :destroy]
          resources :downvotes, only: [:index, :create, :destroy]
        end
      end
      resources :reviews, only: [:index, :show, :create]
    end
  end

  # resources :users, :only =>[:show, :index]

  devise_for :users
  resources :users, only: [:show]
  scope "/admin" do
    resources :users, only: [:index, :destroy]
    resources :reviews, only: [:index]
  end
end

app/models/meme.rb
class Meme < ApplicationRecord
  validates :name, presence: true
  validates :img_url, presence: true

  belongs_to :category
  belongs_to :user
  has_many :reviews
end

app/controllers/api/v1/memes_controller.rb
class Api::V1::MemesController < Api::V1::BaseController

  def show
    @meme = Meme.find(params[:id])
    @reviews = @meme.reviews
    respond_with @reviews, json: @reviews
  end

end

app/controllers/memes_controller.rb
class MemesController < ApplicationController
  before_action :authenticate_user!

  def show
    @meme = Meme.find(params[:id])
    @reviews = @meme.reviews
    @review = Review.new
    @rating_collection = Review::RATINGS
    @users = User.all
    @usershash = Hash.new
    @users.each do |user|
      @usershash[user.id] = user.username
    end
    @user = current_user.username
    @avatar = current_user.avatar
  end

  def new
    @category = Category.find(params[:category_id])
    @user = current_user.id
    @meme = Meme.new
  end

  def create
    @category = Category.find(params[:category_id])

    if user_signed_in?
      @user = current_user
      @meme = Meme.new(meme_params)
      @meme.category = @category
      @meme.user = @user

      if @meme.save
        @category.memes << @meme
        flash[:notice] = "Meme successfully added"
        redirect_to category_path(@category)
      else
        flash[:notice] = @meme.errors.full_messages.to_sentence
        @memes = @category.memes
        render '/categories/show'
      end

    else
      flash[:notice] = "You must be logged in to do that"
      redirect_to category_path(@category)
    end
  end

  def destroy
    @meme = Meme.find(params[:category_id])
    @category = @meme.category
    @meme.destroy
    flash[:notice] = "Meme Deleted!"
    redirect_to category_path(@category)
  end

  private

  def meme_params
    params.require(:meme).permit(:name, :img_url, :user_id)
  end

end

app/views/memes/_form.html.erb
<%= form_for [@category, @meme] do |f| %>

<div class="meme_form">
  <h3>Add a meme!</h3>
  <div>
    <%= f.label :name, "Name" %>
    <%= f.text_field :name, :class => 'form' %>
  </div>

  <div>
    <%= f.label :img_url, "Image Url" %>
    <%= f.text_field :img_url, :class => 'form' %>
  </div>

  <div>
    <%= f.hidden_field :user_id %>
  </div>
  <%= f.submit "Add Meme" %><br>
  <%= link_to "Back", :back %>
</div>

<% end %>

app/views/memes/new.html.erb
<% if @meme.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@meme.errors.count, "error") %> prohibited this meme from being saved:</h2>

      <ul>
      <% @meme.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<%= render "form" %>

app/views/memes/show.html.erb
<div class="meme_show">
<h1><%= @meme.name %></h1>
<% if @meme.user %>
  <p>Created by: <%= @meme.user.username %></p>
<% end %>
<img src="<%= @meme.img_url%>" class="meme-show">

<h3>Reviews of <%= @meme.name %>:</h3>

<div id='reviewsDiv' data-users='<%= @usershash.to_json %>' data-id='<%= @meme.id %>' data-user='<%= @user %>' data-avatar='<%= @avatar %>'>
</div>

<% if current_user.admin %>
  <%= link_to "Delete Reviews", reviews_path %>
<% end %>
<% if current_user.nil? == false && current_user.admin == true %>
    <div class={@meme.id}><%= link_to "Delete Meme", category_meme_path(@meme), method: :delete, id: "delete-meme-#{@meme.id}" %></div>
<% end %>
<%= render "reviews/new" %>