config/routes.rb
Rails.application.routes.draw do

  root "categories#index"

  post "/archive_user", to: "users#archive_user"


  resources :categories, except: [:edit] do
    resources :memes, except: [:edit, :index]
  end

  resources :memes, only: [:show] do
    resource :reviews, except: [:edit, :show, :index]
  end


  namespace :api do
    namespace :v1 do
      resources :categories, only: [:index, :show, :create] do
        resources :memes, only: [:show, :create]
      end
      resources :memes, only: [:show, :create] do
        resources :reviews, only: [:index, :show, :create] do
          resources :upvotes, only: [:index, :create, :destroy]
          resources :downvotes, only: [:index, :create, :destroy]
        end
      end
      resources :reviews, only: [:index, :show, :create]
    end
  end

  # resources :users, :only =>[:show, :index]

  devise_for :users
  resources :users, only: [:show]
  scope "/admin" do
    resources :users, only: [:index, :destroy]
    resources :reviews, only: [:index]
  end
end

app/models/category.rb
class Category < ApplicationRecord
  validates :name, presence: true, uniqueness: true
  validates :image_url, presence: true

  has_many :memes
  def self.search(search)
    where("name ILIKE ?", "%#{search}%")
  end
end

app/controllers/api/v1/categories_controller.rb
class Api::V1::CategoriesController < ApplicationController
  skip_before_filter :verify_authenticity_token

  def index
    @categories = Category.all
    render json: @categories
  end

 #  def create
 #    data = JSON.parse(request.body.read)
 #   @category = Category.new(name: data["name"], image_url: data["image_url"])
 #   if @category.save!
 #     @categories = Category.all
 #     @categories.order(:id)
 #     render json: @categories
 #   else
 #     render json: {message: "Did not work"}, status: 404
 #   end
 # end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  def index
    @categories = Category.all
    respond_to do |format|
      format.html
      format.json { render json: @categories }
    end
    if params[:search]
      @categories = Category.search(params[:search]).order("created_at DESC")
      @search_term = params[:search]
    else
      @categories = Category.all.order("created_at DESC")
    end
  end

  def show
    @category = Category.find(params[:id])
    @memes = @category.memes
    @meme = Meme.new
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(params_strong)
    if @category.save
      flash[:notice] = "Category added successfully!"
      redirect_to categories_path
    else
      flash[:notice] = @category.errors.full_messages.to_sentence
      render :new
    end
  end

  def destroy
    @category = Category.find(params[:id])
    @category.destroy
    flash[:notice] = "Category Deleted!"
    redirect_to root_path
  end


  private

  def params_strong
    params.require(:category).permit(
    :name,
    :image_url
    )
  end
end

app/views/categories/index.html.erb
<h3>Meet Your Next Favorite Meme</h3>

<% if @categories.blank? %>
  <h4>There are no categories containing the term <%= params[:search] %>.</h4>
<% end %>

<% if @categories.length < 100 && @categories.length > 0 %>
  <h4>Meme Categories that match your search: <%= @search_term %></h4>
  <ul class="search-results" id="main-page">
    <% @categories.each do |category| %>
      <li><a id=<%=category.id%> href="/categories/<%= category.id%>"><img src="<%= category.image_url%>" class="meme-search"></a></li>
    <% end %>
  </ul>
<% end %>

<div id='App'></div>

app/views/categories/new.html.erb
<h1> New Category Form: </h1>
  <%= form_for (@category) do |f| %>

    <% if @category.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@category.errors.count, "error") %> prohibited this category from being saved:</h2>
        <ul>
        <% @category.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

  <div class="field">
    <%= f.label :name, "Category Name" %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :image_url, "Category URL" %><br />
    <%= f.text_field :image_url %><br />
  </div>
  <div>
    <%= f.submit(value="Add Category") %>
  </div>
<% end %>

<%= link_to "Back", categories_path %>

app/views/categories/show.html.erb
<div class="categories_show">
    <h1><%= @category.name %></h1>
    <img src='<%= @category.image_url %>' class="base-img" />
<ul>
<% if current_user.nil? == false && current_user.admin == true %>
  <div class={@category.id}><%= link_to "Delete Category", category_path, method: :delete, id: "delete-category-#{@category.id}" %></div>
<% end %>
<% @memes.each do |meme| %>
  <a id="<%= meme.id %>" href="/memes/<%= meme.id %>"><img src='<%= meme.img_url %>' class="category-results"></a>
  <% if current_user.nil? == false && current_user.admin == true %>
    <div class={meme.id}><%= link_to "Delete Meme", category_meme_path(meme), method: :delete, id: "delete-meme-#{meme.id}" %></div>
  <% end %>
<% end %>
</ul>

<%= render "memes/form" %>
</div>