config/routes.rb
Rails.application.routes.draw do

  root "categories#index"

  post "/archive_user", to: "users#archive_user"


  resources :categories, except: [:edit] do
    resources :memes, except: [:edit, :index]
  end

  resources :memes, only: [:show] do
    resource :reviews, except: [:edit, :show, :index]
  end


  namespace :api do
    namespace :v1 do
      resources :categories, only: [:index, :show, :create] do
        resources :memes, only: [:show, :create]
      end
      resources :memes, only: [:show, :create] do
        resources :reviews, only: [:index, :show, :create] do
          resources :upvotes, only: [:index, :create, :destroy]
          resources :downvotes, only: [:index, :create, :destroy]
        end
      end
      resources :reviews, only: [:index, :show, :create]
    end
  end

  # resources :users, :only =>[:show, :index]

  devise_for :users
  resources :users, only: [:show]
  scope "/admin" do
    resources :users, only: [:index, :destroy]
    resources :reviews, only: [:index]
  end
end

app/controllers/api/v1/reviews_controller.rb
class Api::V1::ReviewsController < Api::V1::BaseController

  def index
    @meme = Meme.find(params[:meme_id])
    @reviews = @meme.reviews
    respond_with @reviews, json: @reviews
  end

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :authenticate_user!

  def index
    if current_user.admin
      @reviews = Review.all
    end
  end


  def new
   @meme = Meme.find(params[:meme_id])
   @user = current_user.id
   @review = Review.new
   @review.meme = @meme
   @rating_collection = Review::RATINGS
 end

  def create
    @meme = Meme.find(params[:meme_id])
    @user = current_user
    @review = Review.new(params_strong)
    @review.meme = @meme
    @review.user = @user
    if @review.save
      UserMailer.notice(@review).deliver
      flash[:notice] = "Review added successfully"
      redirect_to controller: 'memes', action: 'show', id: params[:meme_id]
    else
      flash[:notice] = @review.errors.full_messages.to_sentence
      @reviews = @meme.reviews
      @rating_collection = Review::RATINGS
      render '/memes/show'
    end
  end

  def destroy
    @review = Review.find(params[:meme_id])
    @meme = @review.meme
    @review.destroy
    flash[:notice] = "Review Deleted!"
    redirect_to meme_path(@meme)
  end

  private

   def params_strong
     params.require(:review).permit(
       :rating,
       :body
     )
   end
end

app/views/reviews/_new.html.erb
<%= form_for [@meme, @review] do |f| %>
<div class="review_form">
  <div class="review_buttons">
    <%= f.label(:rating, "Rating") %>
    <%= f.collection_radio_buttons(:rating, @rating_collection, :first, :last) %>
  </div>

  <div>
    <%= f.label(:body, "Comment:") %>
    <%= f.text_field(:body) %>
  </div>

  <div>
    <%= f.hidden_field :user_id %>
  </div>

  <div>
    <%= f.submit("Submit Review") %>
  </div>
  <%= link_to "Back", :back %>
</div>

<% end %>

app/views/reviews/_show.html.erb
<div id='reviewsDiv'></div>

app/views/reviews/index.html.erb
<% if current_user.admin %>
  <ul class="reviews">
    <% @reviews.each do |review| %>
      <div class="review">
        <h6> Meme: <%= review.meme.name %> </h6>
        <h6> Posted by: <%= review.user.username %> </h6>
        <li><% review.rating.times do %>♨️<% end %> - <%= review.body %>
        <% if current_user.nil? == false && current_user.admin == true %>
          <div class={review.id}><%= link_to "Delete Review", meme_reviews_path(review), method: :delete, id: "delete-#{review.id}" %></div>
        <% end %></li>
      </div>
    <% end %>
  </ul>
<% else %>
  <%= "Access denied, admin privileges required" %>
<% end %>

<%= link_to "Main Page", categories_path %>