config/routes.rb
Rails.application.routes.draw do

  root "categories#index"

  post "/archive_user", to: "users#archive_user"


  resources :categories, except: [:edit] do
    resources :memes, except: [:edit, :index]
  end

  resources :memes, only: [:show] do
    resource :reviews, except: [:edit, :show, :index]
  end


  namespace :api do
    namespace :v1 do
      resources :categories, only: [:index, :show, :create] do
        resources :memes, only: [:show, :create]
      end
      resources :memes, only: [:show, :create] do
        resources :reviews, only: [:index, :show, :create] do
          resources :upvotes, only: [:index, :create, :destroy]
          resources :downvotes, only: [:index, :create, :destroy]
        end
      end
      resources :reviews, only: [:index, :show, :create]
    end
  end

  # resources :users, :only =>[:show, :index]

  devise_for :users
  resources :users, only: [:show]
  scope "/admin" do
    resources :users, only: [:index, :destroy]
    resources :reviews, only: [:index]
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "goodmemes" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "application", 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>

  <link rel="stylesheet" type="text/css" href="//fonts.googleapis.com/css?family=Actor" />

<div class="top-bar">
  <div class="top-bar-title">
    <a class="logo" href="/">goodmemes 👌</a>
  </div>
  <div id="responsive-menu">
  <div class="top-bar-left">
    <ul class="menu">
      <%= form_tag(categories_path, :method => "get", id: "search-form") do %>
        <li><%= text_field_tag :search, params[:search], placeholder: "Search Categories" %></li>
      <% end %>
    </ul>
  </div>
  <div class="top-bar-right">
        <% if user_signed_in? %>
          <ul class="dropdown menu" data-dropdown-menu>
            <li>
            <%= link_to current_user.email, user_path(current_user.id) %>
              <ul class="menu vertical">
                <% if current_user.admin == true  %>
                <li><%= link_to 'View All Users', users_path, :class => 'navbar-link' %></li>
                <% end %>
                <li><%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %></li>
                <li><%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link' %></li>
              </ul>
            </li>
        <% else %>
      <span><%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %></span><!--
          --><span><%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %></span>
        <% end %>
    </ul>
  </div>
  </div>
</div>

  <body>

    <% if notice %>
      <p class="alert alert-success"><%= notice %></p>
    <% end %>
    <% if alert %>
      <p class="alert alert-danger"><%= alert %></p>
    <% end %>

    <%= yield %>

  </body>
</html>